[program:Xvnc]
command=/usr/bin/Xvnc %(ENV_DISPLAY)s -geometry %(ENV_VNC_RESOLUTION)s -rfbport %(ENV_VNC_PORT)s %(ENV_VNC_OPTIONS)s
autostart=%(ENV_AUTO_START_VNC)s
autorestart=true
# stdout_logfile=/var/log/Xvnc.log
# stderr_logfile=/var/log/Xvnc.err.log
